#!/bin/bash

# Usage check
if [ "$#" -ne 1 ]; then
    echo "Usage: $0 <cleaned_tsv_file>" >&2
    exit 1
fi

file="$1"

awk -F'\t' '
NR == 1 { next }  # Skip header line
{
    if ($13 != "") mechanics[$13]++
    if ($14 != "") domains[$14]++
}
END {
    for (m in mechanics) {
        if (mechanics[m] > max_mech_count) {
            max_mech = m
            max_mech_count = mechanics[m]
        }
    }
    print "The most popular game mechanic is " max_mech " found in " max_mech_count " games"

    for (d in domains) {
        if (domains[d] > max_domain_count) {
            max_domain = d
            max_domain_count = domains[d]
        }
    }
    print "The most game domain is " max_domain " found in " max_domain_count " games"
}
' "$file"